### ISSUE TITLE
Deprecated functions in App-Publisher

### ISSUE THREAD

**Issue by m-lenz** [eclipse/kuksa.apps#12]
`yaml.load(__config_file)` should be replaced with `yaml.load(__config_file, Loader=yaml.FullLoader)` to conform to newer standards and eliminate errors

**Comment by m-lenz** [comment]
kuksa-publisher returns : `kuksa-publisher.py:45: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.`

**Comment by rai20** [comment]
Yes needs to be updated. Thanks.
But works nonetheless (with warnings).

**Comment by SebastianSchildt** [comment]
Changing seems to break it on a standard Ubuntu Python3 installation

```
sebastian@BionicBox:~/kuksa.apps/kuksa-app-publisher$ python3 kuksa-publisher.py test.yaml 
Traceback (most recent call last):
  File "kuksa-publisher.py", line 236, in <module>
    publish_app(args.config_file)
  File "kuksa-publisher.py", line 45, in publish_app
    y=yaml.load(__config_file, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'
sebastian@BionicBox:~/kuksa.apps/kuksa-app-publisher$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> yaml.__version__
'3.12'
>>> 
```

See also https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader

Since is just a support tool, and not on the actual platform itself I would vote, to not change this now.

**Comment by SebastianSchildt** [comment]
safe_load seems a workable compromise... PR incoming....
