### ISSUE TITLE
App-Publisher ignores newapp-Flag

### ISSUE THREAD

**Issue by m-lenz** [eclipse/kuksa.apps#13]
Inside the `YAML`- File a the `newapp`-flag exists to differentiate between new releases and updates. However, the flag is ignored and always set to `false`, which prevents new apps from being uploaded.

**Comment by rai20** [comment]
Where exactly?  Which YAML file?

is it in the kuksa-publisher.py?
I see "False" is set as default in argparser but that the value changes when '-n' and '-r' is passed as cmd line argument.

Is this an observation made while testing or looking at the code?

**Comment by m-lenz** [comment]
While updating the `YAML`- Files with ne ips etc. I stumbled upon this.
In general it affects all files. 
I tested the publisher(basic prints of params) with edited `YAML`s . When I wasn't able to change the parameter `newapp` to `true`, I looked at the code in order to figure it out.

I tried various positions inside the `YAML`-Files for the `newapp`-flag to be recognized, but it always returns false.

**Comment by m-lenz** [comment]
Publishing an App using

1. `-n` Flag = new App
 ```
Hawkbit connection error. Check your Hawkbit's IP in the propreties file!
App already exists in the appstore. Therefore no new app created.
publish anyway
No app with the passed name found in Hawkbit
```
> So apparently, Hawkbit can't be reached

2. `-r` flag = existing app
```
No app with the passed name found in Hawkbit.
```
>  HawkBit works, but doesn't find an existing App with the same name

**Comment by ghost** [comment]
@m-lenz Could you please briefly comment why you closed the issue? Thanks!

**Comment by m-lenz** [comment]
The error occurs not by misinterpreting the parameters/flags but rather by unfinished code.

So i closed this issue and created [another issue](https://github.com/eclipse/kuksa.apps/issues/16) with the corresponding description
