### ISSUE TITLE
APP-Publisher does not conform to our Docker-standards

### ISSUE THREAD

**Issue by m-lenz** [eclipse/kuksa.apps#14]
`docker`-images should yield the prefix `DOCKER_` or `SIMPLE_` to indicate if they are `docker` or `python` applications. 

Regardless of this, the `kuksa-app-publisher` generates tape-archives missing these prefixes.

Message:
> /tmp/``<target>``/Kuksa-Traccar-0.1.0.tar
I do not quite know what to do with this, so I will just download
Download only
Done: 200

Manually named images work as intended
> tmp/``<target>``/DOCKER_appmanager.tar
Careful analysis and extensive checks have revealed this to be a docker image. Yummy
Trying to deploy docker image in /tmp/``<target>``/DOCKER_appmanager.tar
Image imported: Loaded image ID: sha256:`xyz`
Trying to start image sha256:`xyz`

**Comment by rai20** [comment]
with the new "kuksa-appmanager" there is no need to name the docker tarballs in a particular way. They should work regardless of that. But this works only with a docker app at the moment. We will update this to also support native apps soon. Kuksa-appmanager is the preferred appmanager. This is the one which works with the new appstore.

The "kuksa-hawkbit" downloader required a specific name to work, but this will be anyway removed from the repo shortly. So i recommend you do not use/test this.

**Comment by m-lenz** [comment]
If I download an app, which yields the proper Prefix, the app-man works for me.
If the app had no prefix, it will just be downloaded and wont be deployed.
In HawkBit the `Action history` for the target shows a failed push in this case.

But if naming conventions will change soon, I wont invest more time into this topic.

**Comment by SebastianSchildt** [comment]
I think this is obsolete and can be closed @rohoet . As pointed out the the DOCKER_ and SIMPLE_ prefixes belonged to the first Hawkbit integration which since has been removed from the repository. In case of problems with current appmanager open a new issue
