### ISSUE TITLE
App-Publisher never re-publishes

### ISSUE THREAD

**Issue by m-lenz** [eclipse/kuksa.apps#16]
## Publishing an App using

1. `-n` Flag = publish new
```
Category: 354
error Hawkbit connection error. Check your Hawkbit's IP in the propreties file!
App already exists in the appstore. Therefore no new app created.
{'content': [], 'total': 0, 'size': 0}
No app with the passed name found in Hawkbit.
``` 

> not creating app because it already exists? The only existing data is the category of the app, which was added to the `app-store` some operations ago. The publisher still builds a Dockerfile and saves it locally

[![appstore.png](https://i.postimg.cc/NMg2xd0p/appstore.png)](https://postimg.cc/KKHYGrBM)

2. `-r` flag = update app
```
No app with the passed name found in Hawkbit.
```
>  not updating app , even if `-n` returned an error, because the app already exists

---
> Appanrently has the same origin as [this `app-store`-issue](https://github.com/eclipse/kuksa.cloud/issues/63)

**Comment by m-lenz** [comment]
Also the function `createNewAppCategory` is incomplete (`line 140+`) and returns `1` instead of the correct ID.
```
139    print("Okay! There is already the app category in the appstore but i am not able to get its ID :(
140    therefore I set appCategoryID = 1. ") 
141    return 1  #TODO fix this, check with appstore developers.
```

**Comment by m-lenz** [comment]
## updated config from https://github.com/eclipse/kuksa.cloud/issues/63
---
-  `-n` Flag : Publishing Apps only works, if the `category` set inside the config file was never used before
Publishing a new App with an existing App-Category returns :
```
error AppCategory name already exist. name: Test-new
Okay! There is already the app category in the appstore but i am not able to get its ID :(, therefore I set appCategoryID = 1. 
Category: 1
error App Category should exist!
App already exists in the appstore. Therefore no new app created.
No app with the passed name found in Hawkbit.
```

- `-r` Flag : Update Apps only works, if the `yaml`-file didn't change (Even changing only the version of the app will prevent it from being uploaded). Re-uploading an App with a changed version-number(`version : "1.5.0"` instead of `version : "1.4.0"`) returns: 
```
{'content': [], 'total': 0, 'size': 0}
No app with the passed name found in Hawkbit.
```

While re-uploading with unchanged configs returns no error:
```
{'content': [{'id': 653, 'vendor': 'Bosch', 'createdBy': 'admin', 'lastModifiedBy': 'admin', 'lastModifiedAt': 1558609545053, 'type': 'application', '_links': {'self': {'href': 'http://hawkbit-appstacle.westeurope.cloudapp.azure.com:8080/rest/v1/softwaremodules/653'}}, 'description': 'This is a Traccar app for GPS tracking', 'deleted': False, 'createdAt': 1558604539370, 'version': '1.4.0', 'name': 'Traccar'}], 'total': 1, 'size': 1}
Deleted the existing artifacts in hawkbit.
653
found some  <Response [201]>
Uploaded the artifacts to Hawkbit
```

**Comment by SebastianSchildt** [comment]
@rai20 Is this still/was this ever a problem? Should it be fixed by code or documentation?

That "-r" does not work with changed versions is either intended (should be in readme) or a bug (should be changed)

**Comment by daleonpz** [comment]
I faced the same problem when trying to upload a new app with `-n`

```
AppCategory name already exist. name: kuksa-test
Okay! There is already the app category in the appstore but i am not able to get its ID :(, therefore I set appCategoryID = 1. 
App Category should exist!
App already exists in the appstore. Therefore no new app created.
No app with the passed name found in Hawkbit.
```
I tried different names, nothing worked. But I the application category was actually added. 

![Screenshot from 2019-08-01 16-22-20](https://user-images.githubusercontent.com/10763790/62301269-93c8db00-b478-11e9-82a5-6b6828540fb9.png)

**Comment by raipratheek** [comment]
As a workaround change the name of the app to something totally new in the .yaml file and use -n flag. This should work.

Example:
say if this app does not work

![grafik](https://user-images.githubusercontent.com/28050527/62301590-308b7880-b479-11e9-8a67-4e0ea60f91b6.png)

change  name "Dashboard" to "Dashboard2" or soemthing like that and use -n flag.

Add more comments if it does not work.

**Comment by daleonpz** [comment]
I tried also that and didn't work.

**Comment by rai20** [comment]
are you sure if the appstore and hawkbit are configured properly?
it could be that the hawkbit ip address is not configured with appstore. 

If the config is also properly done. Then I need to look into this issue.

**Comment by m-lenz** [comment]
@raipratheek knows what to do. After that he will close this issue

**Comment by rai20** [comment]
This is no longer an issue. This could be closed.
