### ISSUE TITLE
APP-Publisher uses wrong protocol (http instead of https)

### ISSUE THREAD

**Issue by m-lenz** [eclipse/kuksa.apps#17]
the new HawkBit server uses `https` rather than simple `http` 

In order to function with the new HawkBit, change the following lines
`Line 137: response = requests.post('http:// `

and
`Line 173: response = requests.post('http:// `

inside the [publisher](https://github.com/eclipse/kuksa.apps/blob/master/kuksa-app-publisher/kuksa-publisher.py) to read `https` instead of `http` to fix the issue

**Comment by ghost** [comment]
A good approach would be to replace the configuration properties `appstore.ip-address` and `hawkbit.ip-address` by `appstore.url` and `hawkbit.url` and use them accordingly. That way developers could choose whether they want to do HTTPS or HTTP (e.g. for testing locally). We would also get closer to having common configuration options in the various parts of the system - e.g. the appstore itself also uses a `hawkbit.url`.
