### ISSUE TITLE
Apps hard-coded App-store / HawkBit IP error

### ISSUE THREAD

**Issue by m-lenz** [eclipse/kuksa.apps#21]
## Appstore
All apps currently expect an instance of the `appstore` on `localhost:8082` this should be changed to the real Appstore

AGL does not ship with an local app-store so this config won't work on the dedicated hardware

## HawkBit
all apps currently also yield the incorrect IPs for the HawkBit service.
```
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='11.11.111.11', port=8080): Max retries exceeded with 
 (Caused by NewConnectionError: Failed to establish a new connection: [Errno 101] Network is unreachable',))
```

EDIT: deleted links since they are a hazard

**Comment by rai20** [comment]
The .yaml files are only references (examples). It is up to the user to modify these files accordingly to make it work. That means change the ip-address to a valid one and it should work!
For test purposes you may need to do this using some script or hard code your test IP-Addresses.

**Comment by m-lenz** [comment]
closed due to duplication https://github.com/eclipse/kuksa.apps/issues/20#issuecomment-498677841
